app:
  resourceName: "vat-calculator"
  version: @project.version@

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: vat-calculator
  profiles:
    active: prod
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false